inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.rails.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Exclude:
    - Gemfile
    - Gemfile.lock
    - db/schema.rb

Security/Eval:
  Exclude:
    - lib/tasks/**/*.rake
    - config/initializers/configurable.rb
