version: "3.3"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hurricane-farm
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - env/app.env
