default: &default
  adapter: postgresql
  database: hurricane-farm_production
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_ROOT_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_ROOT_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default
  database: hurricane-farm_development
  pool: 10

test:
  <<: *default
  database: hurricane-farm_test
  pool: 5