default: &default
  adapter: postgresql
  database: <%= ENV.fetch('POSTGRES_DB') %>
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>

development:
  <<: *default
  pool: 10

test:
  <<: *default
  pool: 5